### ISSUE TITLE
SHA1 on the site does not match download

### ISSUE THREAD

**Issue by rladams** [weiss/nsca-ng#5]
[2022/09/28 23:07:19] adamsrl@tahm [0] |0|
~/tmp
% wget https://nsca-ng.org/download/nsca-ng-1.6.tar.gz 
--2022-09-28 23:07:25--  https://nsca-ng.org/download/nsca-ng-1.6.tar.gz
Resolving nsca-ng.org (nsca-ng.org)... 194.59.205.169, 2a03:4000:34:1a8:94a2:aaff:fe4f:c926
Connecting to nsca-ng.org (nsca-ng.org)|194.59.205.169|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 454788 (444K) [application/octet-stream]
Saving to: ‘nsca-ng-1.6.tar.gz’

nsca-ng-1.6.tar.gz            100%[================================================>] 444.13K  --.-KB/s    in 0.1s    

2022-09-28 23:07:25 (3.10 MB/s) - ‘nsca-ng-1.6.tar.gz’ saved [454788/454788]

[2022/09/28 23:07:25] adamsrl@tahm [0] |0|
~/tmp
% wget https://nsca-ng.org/download/nsca-ng-1.6.tar.gz.sha1
--2022-09-28 23:07:36--  https://nsca-ng.org/download/nsca-ng-1.6.tar.gz.sha1
Resolving nsca-ng.org (nsca-ng.org)... 194.59.205.169, 2a03:4000:34:1a8:94a2:aaff:fe4f:c926
Connecting to nsca-ng.org (nsca-ng.org)|194.59.205.169|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 61 [application/octet-stream]
Saving to: ‘nsca-ng-1.6.tar.gz.sha1’

nsca-ng-1.6.tar.gz.sha1       100%[================================================>]      61  --.-KB/s    in 0s      

2022-09-28 23:07:37 (33.5 MB/s) - ‘nsca-ng-1.6.tar.gz.sha1’ saved [61/61]

[2022/09/28 23:07:37] adamsrl@tahm [0] |0|
~/tmp
% cat nsca-ng-1.6.tar.gz.sha1
f6c5f4ce1c70be825be66772949cddd332c03e09 *nsca-ng-1.6.tar.gz

[2022/09/28 23:07:42] adamsrl@tahm [0] |0|
~/tmp
% sha1 nsca-ng-1.6.tar.gz
SHA1 (nsca-ng-1.6.tar.gz) = 413da3201a02c8cecc3f949fec0f022fd311076c

[2022/09/28 23:07:49] adamsrl@tahm [0] |0|
~/tmp
% openssl dgst -sha1 < nsca-ng-1.6.tar.gz
(stdin)= 413da3201a02c8cecc3f949fec0f022fd311076c

**Comment by rladams** [comment]
Nvm, github moved me on login from the perl repo. This is the right one.

**Comment by weiss** [comment]
Thanks.  I didn't manage to figure out how the incorrect SHA1 sum was created, but the release tarball is the original one (and [the GPG signature][1] is fine), so I've corrected [the SHA1 sum file][2], now.

[1]: https://nsca-ng.org/download/nsca-ng-1.6.tar.gz.asc
[2]: https://nsca-ng.org/download/nsca-ng-1.6.tar.gz.sha1
